version: '3' 
services:

  cassandra:
    image: ${CASSANDRA_IMAGE_NAME:-bitnami/cassandra:latest}
    container_name: cassandra
    volumes:
      - ~/apps/cassandra:/var/lib/cassandra
    ports:
      - 9042:9042 #cqlsh
      - 7199:7199 #jmx
      - 7000:7000 #internode communication
      - 7001:7001 #tls internode
      - 9160:9160 #client api
    environment:
      CASSANDRA_USE_ASTRA: "false" 
      CASSANDRA_USER: "cassandra" 
      CASSANDRA_PASSWORD: "cassandra" 
      CASSANDRA_LOCAL_DC: "datacenter1" 
      CASSANDRA_CONTACT_POINTS: "db:9042"
      CASSANDRA_KEYSPACE_CQL: "CREATE KEYSPACE test_keyspace WITH REPLICATION = {'class':'SimpleStrategy','replication_factor':1};" 
      #CASSANDRA_LISTEN_ADDRESS: "192.168.64.2" 
      #CASSANDRA_RPC_ADDRESS: "192.168.64.2"    
      MONITORING_PROMETHEUS: "false"
      MONITORING_GRAFANA: "false"
      DISTRIBUTED_TRACING_ENABLED: "false"

# cassandra:
#     image: bitnami/cassandra:latest
#     container_name: cassandra
#     volumes:
#       - cassandra_data:/bitnami
#     ports:
#       - 9042:9042 #cqlsh
#       - 7199:7199 #jmx
#       - 7000:7000 #internode communication
#       - 7001:7001 #tls internode
#       - 9160:9160 #client api
#     networks:
#       net_pet:
#         ipv4_address: 172.27.1.5